# 1. Tensor

In [4]:
import torch

In [10]:
t1 = torch.zeros(4,2)
print(t1)
print(t1.shape)
print(t1.dtype)
print(t1.device)

t2 = torch.rand(2)
print("t2: ")
print(t2)
print(t2.shape)

print("\n---after unsqueeze---")
t2_add_rank = t2.unsqueeze(0)
print(t2_add_rank)
print(t2_add_rank.shape)

t4 = torch.rand(192) # 3*8*8
print(t4.shape)

t4 = t4.reshape(3, 8, 8)
print("\n---after reshape---")
print(t4.shape)

t4 = t4.permute(1,2,0)
print("\n---after permute---")
print(t4.shape)

# Attribute - device
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(device)
# t1_gpu = t1.cuda(device) 
# print(t1_gpu.device)     
# print(t1.device)         

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])
torch.Size([4, 2])
torch.float32
cpu
t2: 
tensor([0.1567, 0.0490])
torch.Size([2])

---after unsqueeze---
tensor([[0.1567, 0.0490]])
torch.Size([1, 2])
torch.Size([192])

---after reshape---
torch.Size([3, 8, 8])

---after permute---
torch.Size([8, 8, 3])
cpu


In [11]:
# 실제 값 이동 확인
t5 = torch.rand(12)
print('\n', t5)
t5 = t5.reshape(3,2,2)
print('\n', t5)
t5= t5.permute(1,2,0) #(2,2,3)
print('\n',t5)


 tensor([0.1940, 0.0196, 0.1662, 0.2216, 0.9325, 0.3869, 0.6377, 0.5002, 0.8160,
        0.7854, 0.4394, 0.3555])

 tensor([[[0.1940, 0.0196],
         [0.1662, 0.2216]],

        [[0.9325, 0.3869],
         [0.6377, 0.5002]],

        [[0.8160, 0.7854],
         [0.4394, 0.3555]]])

 tensor([[[0.1940, 0.9325, 0.8160],
         [0.0196, 0.3869, 0.7854]],

        [[0.1662, 0.6377, 0.4394],
         [0.2216, 0.5002, 0.3555]]])


In [2]:
import numpy as np
import torch

In [3]:
# basic operations
# numpy에서 tensor로 옮기는 과정이 필요하다

# convert numpy -> tensor
num_array = np.array([[1,2],[3,4]])
t5 = torch.Tensor(num_array)
print(type(num_array))
print(num_array)
print(type(t5))
print(t5)

<class 'numpy.ndarray'>
[[1 2]
 [3 4]]
<class 'torch.Tensor'>
tensor([[1., 2.],
        [3., 4.]])


In [4]:
# elementwise operations
t6 = torch.ones_like(t5) # tesnor filled w/ value '1' in the same shape of t5
output = t5 + 2 * t6
print(output)

print()
print("exponential: ")
print(torch.exp(output))

tensor([[3., 4.],
        [5., 6.]])

exponential: 
tensor([[ 20.0855,  54.5981],
        [148.4132, 403.4288]])


In [5]:
# broadcasting
vector = torch.ones((2,1)) # shape: (2,1)
broadcast_output = output + vector
print(broadcast_output)

vector_err = torch.ones((3,1)) # shape: (3,1)
# broadcast_output = output + vector_err # Raise Error!

tensor([[4., 5.],
        [6., 7.]])


In [6]:
# dimension reduction
t7  = torch.randn(2,3,4) # shape: (2,3,4) = (0th dim, 1st dim, 2nd dim)
# rank가 3개
# 앞 뒤로 3x4 matrix가 각 1개씩 있다는 것. 즉 2개 있다는 뜻
print(t7)
print()

# argmax는 가장 큰 값을 가진 위치를 뽑는, index를 뽑는 함수
# 'dim = 1'은 dimension 1에 해당하는 것끼리 비교하겠다는 것. 
# dimension 0이 2, 1이 3, 2가 4이므로 여기에서는 앞, 뒤 3X4 matrix에서 3에 해당하는 것 중에서 제일 큰 것의 위치를 뽑겠다.
# 3에 해당하는 것 중에 1개만 뽑으니까 1이 되고, 2X4가 되는 것. 2X4 matrix를 뽑겠다는 생각이다.
t7_argmax = torch.argmax(t7, dim=1)
print(t7_argmax.shape) # rank가 2개로 자동으로 줄었다.
print(t7_argmax)

print()

# rank를 줄이지 않고 유지를 해야할 때가 있다. keepdims = True로 해주면 된다.
print(torch.argmax(t7, 1, keepdims=True).shape) 
# print(torch.argmax(t7, 1, keepdims=True))
# squeeze를 1로 한다는 것은 2X3X4에서 3에 해당하는 것을 줄이겠다는 뜻이다. 2X4가 된다. 위와 동일한 결과가 나온다.
print(torch.argmax(t7, 1, keepdims=True).squeeze(1).shape)

tensor([[[-0.1916,  0.2789, -1.1285,  1.3264],
         [-0.1826,  0.5047, -0.6547, -0.5838],
         [ 1.4835, -0.1682, -0.0951,  1.1563]],

        [[ 1.3895, -0.9026,  0.6342,  0.6280],
         [ 0.5826, -1.6360,  0.6985,  1.7466],
         [-1.0100,  0.3689,  1.5041, -0.3104]]])

torch.Size([2, 4])
tensor([[2, 1, 2, 0],
        [0, 2, 2, 1]])

torch.Size([2, 1, 4])
torch.Size([2, 4])


# Data

torch.utils.data.Dataset
  A python class defining a Dataset
  Called by DataLoader implicitly
  Need to implement the floowing methods:
    __init__: initialize dir/file to read images, transform
    __getitem__:loads data from dataset at a given index
    __len__:returns the size of dataset

torch.utils.data.DataLoader
  Dataset을 model로 전달
  Parameters
    batch_size(default = 1)
    shuffle     
    num_workers # 병렬 처리와 관련된 내용

In [9]:
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

In [10]:
class SimpleDataset(Dataset):

  # Initializes csv_file(annotation) and root_dir storing the data
  # (optional) initializes transformations
  def __init__(self, csv_file=None, root_dir=None):

    #self.csv_file = csv_file
    #self.root_dir = root_dir
    self.x_data = torch.rand(100, 4)
    self.y_data = torch.rand(100, 1)

  # Provides the size of dataset
  def __len__(self):
    return len(self.x_data)

  # Provides a sample data given idx
  def __getitem__(self, idx):
    x = torch.FloatTensor(self.x_data[idx])
    y = torch.FloatTensor(self.y_data[idx])
    return x, y

In [11]:
dataset = SimpleDataset() 
# Number of samples in a mini-batch: 25
# Shuffles dataset before sampling
dataloader = DataLoader(dataset, batch_size=25, shuffle=True)

In [17]:
# collate_fn
# Dataloader의 batch 단위로 input을 process하기 위한 작업(post-processing)
  # e.g. 서로 길이가 다른 input에 zero-padding을 추가해 길이 맞춰주기
  # 길이가 다르면 같은 batch로 묶이지 않는다. ㅡ

def collate_fn(self, data):
  max_len = 10
  batch = []
  for x, y in data:
    x_padded = torch.cat([x, torch.zeros(max_len - x.shape[0])])
    batch.append(x_padded)
  return torch.stack(batch)

In [16]:
dataset = SimpleDataset() 
dataloader = DataLoader(dataset, batch_size=25, shuffle=True)

<function Tensor.size>

# 2. Dataset & Dataloader

In [5]:
# Define dataset & dataloader

import torch
import numpy as np
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
import random

class SimpleDataset(Dataset):

  def __init__(self, csv_file=None, root_dir=None):

    #self.csv_file = csv_file
    #self.root_dir = root_dir

    # set x_data with random length
    n_dataset = 100
    self.x_data = []
    for _ in range(n_dataset):
      random_length = random.randint(5,10)
      self.x_data.append(np.random.randint(0,255,random_length))
    # set y_data
    self.y_data = torch.rand(n_dataset, 1)

    print("SimpleDataset setting done")
    print(f'x_data shape: {len(self.x_data)}')
    print(f'x_data random length (1st, 4th, 46th): {len(self.x_data[0]), len(self.x_data[3]), len(self.x_data[45])}')
    print(f'y_data shape: {self.y_data.shape}')

  # Provides the size of dataset
  def __len__(self):
    return len(self.x_data)

  # Provides a sample data given idx
  def __getitem__(self, idx):
    x = torch.FloatTensor(self.x_data[idx])
    y = torch.FloatTensor(self.y_data[idx])
    return x, y

  # Zero padding
  # dataloader 입장에서 batch로 맞출 때 아래 function을 call한다.
  # zero padding 이외에 다른 목적으로 batch 구성 시 call하고 싶은 function이 있으면 
  # 다르게 정의해줘도 된다. 
  def collate_fn(self, data):
    max_len = 10
    batch = []
    for x, y in data:
      x_padded = torch.cat([x, torch.zeros(max_len - x.shape[0])])
      batch.append(x_padded)
    return torch.stack(batch)

# instance를 하나 만들어준 것
dataset = SimpleDataset()

SimpleDataset setting done
x_data shape: 100
x_data random length (1st, 4th, 46th): (10, 8, 10)
y_data shape: torch.Size([100, 1])


In [6]:
# 100개 중 25개씩 배치를 묶으면 4묶음이 나온다.
dataloader = DataLoader(dataset, batch_size=25, collate_fn=dataset.collate_fn, shuffle=True)
# dataloader = DataLoader(datset, batch_size=25, shuffle True) # Raise Error!

for batch_idx, samples in enumerate(dataloader):
  print("batch idx: ", batch_idx+1)
  print("sample shape: ", samples.shape)

  if batch_idx == len(dataloader)-1:
    print(samples)

  # ... train continued
  # 짧게 나온 것들은 0이 추가되어 있음. zero padding이 되어있다.
  # 같은 길이의 데이터만 return 할 수 있다.

batch idx:  1
sample shape:  torch.Size([25, 10])
batch idx:  2
sample shape:  torch.Size([25, 10])
batch idx:  3
sample shape:  torch.Size([25, 10])
batch idx:  4
sample shape:  torch.Size([25, 10])
tensor([[139.,  82.,  39., 155., 233.,  20., 191., 141., 172.,   0.],
        [ 40.,  31., 109., 162., 156., 201.,  74.,  74., 225.,   0.],
        [133.,  44., 195., 183.,  38., 192.,  59.,  96.,   0.,   0.],
        [167.,  91., 225., 166., 119.,  72., 180.,  91., 155.,   0.],
        [ 94.,  83.,  60., 233., 179.,   0.,   0.,   0.,   0.,   0.],
        [232., 117., 116., 244., 114.,  38., 145.,  76.,  63.,   0.],
        [214., 127., 254.,  66.,  44., 111., 139.,   0.,   0.,   0.],
        [107., 180., 203., 186.,  27., 228.,  70.,   0.,   0.,   0.],
        [ 34., 111., 119., 155., 231.,   6.,  12., 103.,   0.,   0.],
        [ 51., 244.,  71.,  26., 246., 182.,  97., 128., 202.,   0.],
        [ 62.,  94.,  47.,  28.,  23., 198., 218.,   0.,   0.,   0.],
        [ 98.,  24.,  98., 156

#Defining a Model


1. Inherit nn.Module
2. Define __init__
  - weight을 포함하는 trainable layer
3. Define forward
  - weight을 포함하지 않는 fixed operation layer
    - e.g. softmax, relu
  - 위와 같은 함수는 learnable 하지 않기 때문에 init에 써줄 필요 없이
  - forward 함수에 곧바로 써준다.
  - Called automatically by __call__
  - Output = network(input)
4. Types of layers in Pytorch

In [8]:
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

# two-layer example

class Net(nn.Module):
  def __init__(self):
    super(Net, self).__init__()
    self.fc1 = nn.Linear(784,128)
    self.fc2 = nn.Linear(128,64)
    self.classifier = nn.Linear(64,10)
    # MNIST는 10개의 숫자를 classify 하는 것이기 때문에 10으로 설정한 것
    
  def forward(self, x):
    x = x.reshape(-1, 784)
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    return self.classifier(x)

network = Net()
print(network)

Net(
  (fc1): Linear(in_features=784, out_features=128, bias=True)
  (fc2): Linear(in_features=128, out_features=64, bias=True)
  (classifier): Linear(in_features=64, out_features=10, bias=True)
)


#Training a Model

training을 할 때는 update를 해줘야 하고
test를 할 때는 바뀌면 안 되기 때문에 모드를 따로 설정해줘야 한다.

1. Set train mode on
 - Train <-> eval
 - activate/deactivate some layers
 - (e.g., dropout, batch-norm..)

2. Set optimization grad to zero for each mini-batch

3. Copy the data to the device where the model exists.

4. Backpropagation & update parameters.

In [10]:
def train(model, optim, loss_fn, train_loader, epochs, device):
  for epoch in range(epochs):
    train_loss = 0.0
    # Train mode로 전환
    model.train()

    for batch in train_loader:
      # Initialize, gradient를 모두 0으로 만들어준다.
      # gradient를 다 계산해서 쌓을 건데, batch 별로 gradient를 쌓고 update를 하기 때문에
      # 새로운 batch가 들어올 때마다 초기화 해줘야 한다.
      optim.zero_grad()

      input, target = batch
      # GPU 사용 시
      # 앞에서 모델 parameter를 모두 GPU에 올렸다면 아래 둘 다 같이 GPU에 올라가야 오류가 안 생긴다.
      input = input.to(device)
      target = target.to(device)

      output = model(input)
      loss = loss_fn(output, target)
      loss.backward()
      optim.step()
      train_loss += loss.data.item()
    train_loss /= len(train_loader.dataset)

    print(f'Epoch: {epoch+1}, Training Loss: {train_loss}')

# Testing a Model

1. Set evaluation mode on
2. Set autograd engine off
  - Autograd: automatically track gradients

In [26]:
def test(model, loss_fn, device):
  model.eval()
  test_loss = 0.0
  correct = 0

  # with 문으로 감싸주는 이유는 test할 때는 background에서 autograd가 돌 필요가 없기 때문
  with torch.no_grad():
    for batch in test_loader:
      input, target = batch
      # GPU 사용 시
      input = input.to(device)
      target = target.to(device)

      output = model(input)
      loss = loss_fn(output, target)
      test_loss += loss.data.item()
      pred = output.data.max(1, keepdim=True)[1]
      correct += pred.eq(target.data.view_as(pred)).sum().item()
    test_loss /= len(test_loader.dataset)
  print(f'Test Loss: {test_loss:.4f},\t Accuracy: ({100. * correct / len(test_loader.dataset)}%)\n')

In [27]:
optimizer = optim.SGD(network.parameters(), lr=1e-2, momentum = 0.9)
train(network, optimizer, nn.CrossEntropyLoss(), train_loader, num_epochs, device)
test(network, nn.CrossEntropyLoss(), device)

Epoch: 1, Training Loss: 0.0008659676497181257
Epoch: 2, Training Loss: 0.0007285783295713675
Epoch: 3, Training Loss: 0.0006259336510925399
Test Loss: 0.0011,	 Accuracy: (97.77%)



# Saving & Loading a Model

1. Option 1. store parameters & structures of the model

2. Option 2. store each layers' parameters in a python dictionary
  - 이후 모델이 변경되어도 사용 가능
  - key: layer, value: model's weight

3. Pre-trained weights and model from PyTorch

# Preparing dataset(MNIST)

In [28]:
from torch.utils.data import Dataset
from torchvision import datasets
from torchvision.transforms import ToTensor

train_data = datasets.MNIST(
    root = "data",
    train = True,
    download = True,
    transform = ToTensor()
)

test_data = datasets.MNIST(
    root="data",
    train=False,
    download = True,
    transform = ToTensor()
)

# set data loader
batch_size = 64
train_loader = DataLoader(train_data, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(test_data, batch_size=batch_size, shuffle=True)

In [29]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
network.to(device)
print(device)

num_epochs = 3 #3번 돌면서 training을 하겠다.
optimizer = optim.SGD(network.parameters(), lr=1e-2, momentum=0.9)
train(network, optimizer, nn.CrossEntropyLoss(), train_loader, num_epochs, device) # 3번 트레이닝 한 다음에
test(network, nn.CrossEntropyLoss(), device) # 최종 결과를 얻는다.

cpu
Epoch: 1, Training Loss: 0.0005352937669920114
Epoch: 2, Training Loss: 0.0004619765471647649
Epoch: 3, Training Loss: 0.0003846111050195759
Test Loss: 0.0011,	 Accuracy: (98.0%)



# Save 하는 방법

In [31]:
# option 1
# save parameters & structure of model

torch.save(network, "./data/first_network")
loaded_network = torch.load("./data/first_network")
print(loaded_network)
print(type(loaded_network))

Net(
  (fc1): Linear(in_features=784, out_features=128, bias=True)
  (fc2): Linear(in_features=128, out_features=64, bias=True)
  (classifier): Linear(in_features=64, out_features=10, bias=True)
)
<class '__main__.Net'>


In [32]:
# option 2
# maps of each layer's parameters

torch.save(network.state_dict(), "./data/first_network_dict") # dictionary를 save
state_dict = torch.load("./data/first_network_dict")
print(type(state_dict)) # 'collections'는 python 내부 library, python dictionary로 생각하면 된다.

# key는 layer 이름
# 새로 추가해주는 additional_layer는 학습이 안 되어 있다. fc1, fc2, classifier는 학습이 된 layer
network.add_module("additional_layer", nn.Linear(10,10))
print(*network.modules())

<class 'collections.OrderedDict'>
Net(
  (fc1): Linear(in_features=784, out_features=128, bias=True)
  (fc2): Linear(in_features=128, out_features=64, bias=True)
  (classifier): Linear(in_features=64, out_features=10, bias=True)
  (additional_layer): Linear(in_features=10, out_features=10, bias=True)
) Linear(in_features=784, out_features=128, bias=True) Linear(in_features=128, out_features=64, bias=True) Linear(in_features=64, out_features=10, bias=True) Linear(in_features=10, out_features=10, bias=True)


In [36]:
# strict = False ; strict하지 않게 불러오겠다. 안에 weight을 채워넣겠다.
network.load_state_dict(state_dict, strict=False)
# network.load_state_dict(state_dict, strict=True) # Raise Error!
print(network)

Net(
  (fc1): Linear(in_features=784, out_features=128, bias=True)
  (fc2): Linear(in_features=128, out_features=64, bias=True)
  (classifier): Linear(in_features=64, out_features=10, bias=True)
  (additional_layer): Linear(in_features=10, out_features=10, bias=True)
)


In [37]:
# predefine 된 모델
import torchvision.models as models

resnet18 = models.resnet18(pretrained=True)
print(resnet18)

/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /root/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth
100%|██████████| 44.7M/44.7M [00:00<00:00, 196MB/s]

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
  

In [40]:
# 바로 가져다 쓸 수 없는 이유는 마지막 layer인 (fc) : Linear의 out_features가 1000이기 때문이다. 
# 512 x 1000의 데이터, 1000개의 class를 가진 데이터에서 학습했기 때문이다.

# 우리는 class가 10개이다. 그래서 마지막 layer를 바꿔줘야 한다.
# 그러면 pre-trained weight을 활용하면서 우리 데이터에 맞게 적용할 수 있다.
num_classes = 10
last_layer_in_features = resnet18.fc.in_features # 512개의 in_features를 받아오기 위한 것
resnet18.fc = nn.Linear(last_layer_in_features, num_classes) # 512에서 1000이 아니라 10으로 가는 것으로 바꿔치기
print(resnet18)

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
  